// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgN1H3_-UdolPlygEouTcabOj0Mtl0pF8',
    appId: '1:411119878725:web:4a3f5ddf02cef86795192c',
    messagingSenderId: '411119878725',
    projectId: 'invition-4131d',
    authDomain: 'invition-4131d.firebaseapp.com',
    storageBucket: 'invition-4131d.firebasestorage.app',
    measurementId: 'G-5908QYRPFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGKDLV9J--n_dZBGkL-VNunKWyFsXmFfo',
    appId: '1:411119878725:android:9df4eed809edcb2e95192c',
    messagingSenderId: '411119878725',
    projectId: 'invition-4131d',
    storageBucket: 'invition-4131d.firebasestorage.app',
  );
}
